### ISSUE TITLE
Hoodoo::Client response interaction id not populated when response is an error.

### ISSUE THREAD

**Issue by thelollies** [LoyaltyNZ/hoodoo#152]
The interaction id for a request/response is available via the `response_options` Hash in Hoodoo::Client::AugmentedBase. When a call is successful the interaction id is populated correctly, when an error response is received the interaction id is `nil`. Example to reproduce:

```ruby
irb> client.resource( :NotARealResource ).show( 'foo' ).response_options[ 'interaction_id' ]
=> nil
irb> client.resource( :NotARealResource ).list.response_options[ 'interaction_id' ]
=> nil
```

**Comment by pond** [comment]
I do note this in the documentation for `response_options`:

```
      # On success, this Hash may be updated with options describing
      # 'out-of-band' information associated with the response, derived from
      # HTTP headers for HTTP-based transports. Non-HTTP transports still
      # carry HTTP-like headers and apply equally here.
      #
      # For more about the mapping from header to option, see class method
      # Hoodoo::Client::Headers.x_header_to_options. Since Hoodoo itself
      # sets up <tt>X-Interaction-ID</tt> and <tt>X-Service-Response-Time</tt>
      # headers in _most_ cases, you can expect to at least find the options
      # +interaction_id+ and +service_response_time+ set for successful calls.
      #
      # Under some circustances, especially for certain error conditions, the
      # value may be +nil+, though Hoodoo endeavours to avoid this and at
      # least fill in +interaction_id+ where possible.
      #
      attr_accessor :response_options
```

**Comment by pond** [comment]
You've actually found an Alchemy Edge Splitter bug in your specific example. If I create a Client to a "real" grid endpoint, then it raises the 404 in the router but forgets to set `X-Interaction-ID` in the response. If I route to an existing permitted resource on that grid but try to show an item that doesn't exist, I get a service-generated 404 that carries the inbound interaction ID in the response and this does reach all the way back to the client's response options.

If you set up a local DRb discoverer so that the Hoodoo discovery engine itself knows the endpoint is missing, then Hoodoo generates the 404 _on the client side_ before even bothering to send a request (because it doesn't know _where_ to send it). There's no interaction ID then either. The interaction ID only happens if an actual service contact happens, or a front-end guardian component like an Alchemy Edge Splitter is in use which generates interaction IDs instead of Hoodoo.

The Client could make up an interaction ID, but there's no point; there are no permanently logged records of any server interaction in the pure client-side 404 case. The Alchemy Edge Splitter bug should be fixed though.
