### ISSUE TITLE
X-Dated-At header allow some wriggle room

### ISSUE THREAD

**Issue by natashadowse** [LoyaltyNZ/hoodoo#240]
Sometimes very small clock drifts between nodes have the effect of rejecting a valid call because the default to set X-Dated-At header as `Time.now` (if none specified) can be very slightly ahead of the node it's sending the header to which then returns as invalid because the datetime can't be in the future. Would be good to allow a few seconds in the future to allow for these minor clock drifts.

**Comment by pond** [comment]
This relates to the LNZL deployment where Hoodoo services are running in Docker containers across multiple hosts with requests routed over an AMQP-based queue cluster. Inter-resource calls can therefore migrate between hosts over the queue cluster, but an inbound undated request might default to a "Time.now" inside one host, get processed on another, and be faulted because clock drift between those two hosts makes the destination one see a time that's "in the future" from its own clock's perspective.

**Comment by pond** [comment]
Fixed by https://github.com/LoyaltyNZ/hoodoo/pull/247 and released as v2.3.0.
